name: blood_donation_collage
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  google_fonts: ^2.2.0
  get: ^4.6.1
  lottie: ^1.2.1
  sms_autofill: ^2.2.0
  animated_bottom_navigation_bar: ^0.3.2
  firebase_analytics: ^9.0.5
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  cloud_firestore: ^3.1.6
  intl: ^0.17.0
  flutter_progress_hud: ^2.0.0
  url_launcher: ^6.0.18
  image_picker: ^0.8.4+5
  firebase_storage: ^10.2.6
  path_provider: ^2.0.8
  shared_preferences: ^2.0.12
  webview_flutter: ^3.0.0
  date_time_picker: ^2.1.0
  shimmer: ^2.0.0
  focused_menu: ^1.0.5
  firebase_messaging: ^11.2.11
  firebase_messaging_web: ^2.2.9
  flutter_local_notifications: ^9.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lotties/
    - assets/others/
    - assets/healthtips/
    - assets/campaign/
    - assets/doctors/
    - assets/lottie/

