name: donercall
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  get: ^4.6.1
  lottie: ^2.3.2
  sms_autofill: ^2.2.0
  animated_bottom_navigation_bar: ^1.2.0

  #for fcm and working with firebase
  firebase_analytics: ^10.4.1
  firebase_core: ^2.13.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.2.1
  firebase_messaging: ^14.6.1
  firebase_messaging_web: ^3.5.1
  flutter_local_notifications: ^14.1.0
  http: ^0.13.5
  
  intl: ^0.17.0
  flutter_progress_hud: ^2.0.0
  url_launcher: ^6.0.18
  
  shared_preferences: ^2.0.12
  date_time_picker: ^2.1.0
  focused_menu: ^1.0.5
  
  #for permission
  permission_handler: ^10.0.0
  #current location form latandlong
  geolocator: ^9.0.1
  
  #for toast
  fluttertoast: ^8.0.9
  #for map
  google_maps_flutter: ^2.4.0

  app_settings: ^4.2.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/louncher_icon/icon.png"


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/lotties/
    - assets/others/
    - assets/lottie/

 
